workspace:
  base: /drone/src
  path: background-front-system

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - node_modules
    volumes:
      - '/drone/src/background-front-system:/cache'

  build-master:
    image: 'node:10.6.0'
    privileged: true
    commands:
      - 'npm install --registry=https://registry.npm.taobao.org'
      - 'npm run build'
    when:
      branch: master


  public-master:
    image: itanger/drone-docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    commands:
      - 'docker login -u mason@1152146919661410 -p mslmxq2001 registry-vpc.cn-beijing.aliyuncs.com'
      - 'docker build --rm -f Dockerfile -t registry-vpc.cn-beijing.aliyuncs.com/ecsplus/background-front-system .'
      - 'docker push registry-vpc.cn-beijing.aliyuncs.com/ecsplus/background-front-system'
    when:
      branch: master
      event: push


  rancher-master:
    image: itanger/drone-rancher
    url: 'http://39.107.137.109:10080'
    access_key: 8C1BEEFBCABA585C1B95
    secret_key: fDGgVJDjx89F6a5cDozYKfQSXT27YCqeJ2qYmJx3
    service: shuangshi/background-front-system
    docker_image: registry-vpc.cn-beijing.aliyuncs.com/ecsplus/background-front-system'
    start_first: false
    confirm: true
    timeout: 180
    when:
      branch: master
      event: push


  rebuild-cache:
    image: itanger/drone-volume-cache
    rebuild: true
    mount:
      - node_modules
    volumes:
      - '/drone/src/background-front-system:/cache'
